services:
  - type: web
    name: ems-equipment-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
